# Generated by Django 5.0.6 on 2025-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(),
        ),
    ]
